server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active:
#    native
      - vault
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config
        vault:
          authentication:
          token:
          port: 8200
          host: 127.0.0.1
          kvVersion: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"