server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active: vault
  main:
    allow-bean-definition-overriding: true

spring.cloud.vault:
  host: localhost
  port: 8200
  scheme: https
  uri: https://localhost:8200
  connection-timeout: 5000
  read-timeout: 15000
  config:
    token: myroot
spring.config.import: vault://




management:
  endpoints:
    web:
      exposure:
        include: "*"